// Generated by https://quicktype.io

import { User } from "../models/user.model";

export interface LoadUsers {
  ok:         boolean;
  users:      User[];
  uid:        string;
  totalUsers: number;
}

